# Generated by Django 6.0.7 on 2026-07-14 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_vendor_organization_fields'),
        ('franchises', '0003_franchise_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('can_view_leads', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_show_website', models.BooleanField(default=False)),
                ('can_show_documents', models.BooleanField(default=False)),
                ('can_be_verified', models.BooleanField(default=False)),
                ('can_be_promoted', models.BooleanField(default=False)),
                ('max_franchises', models.PositiveIntegerField(blank=True, null=True)),
                ('max_documents_per_franchise', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly', 'name'],
                'indexes': [models.Index(fields=['slug'], name='billing_pla_slug_cb45bd_idx'), models.Index(fields=['is_active'], name='billing_pla_is_acti_0aba70_idx')],
            },
        ),
        migrations.CreateModel(
            name='FranchisePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('featured', 'Featured'), ('search_boost', 'Search boost'), ('verified_badge', 'Verified badge'), ('category_top', 'Category top'), ('homepage_featured', 'Homepage featured')], max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='franchises.franchise')),
            ],
            options={
                'ordering': ['-priority', '-starts_at'],
                'indexes': [models.Index(fields=['franchise', 'status'], name='billing_fra_franchi_e19975_idx'), models.Index(fields=['promotion_type', 'status'], name='billing_fra_promoti_36c20f_idx'), models.Index(fields=['starts_at', 'ends_at'], name='billing_fra_starts__fec442_idx'), models.Index(fields=['priority'], name='billing_fra_priorit_a3cb13_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('manual_payment_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='not_required', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'ordering': ['-starts_at', 'organization__name'],
                'indexes': [models.Index(fields=['organization', 'status'], name='billing_org_organiz_4c38fc_idx'), models.Index(fields=['starts_at', 'ends_at'], name='billing_org_starts__3c1613_idx'), models.Index(fields=['manual_payment_status'], name='billing_org_manual__7df1fa_idx')],
            },
        ),
    ]
