# Generated by Django 6.0.7 on 2026-07-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('location_report', 'Raport lokalizacji'), ('specialist_match', 'Dopasowanie specjalisty')], max_length=30)),
                ('specialist_area', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W realizacji'), ('completed', 'Zakończone'), ('cancelled', 'Anulowane')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type', 'status'], name='billing_inv_service_62837f_idx'), models.Index(fields=['email'], name='billing_inv_email_dbd63c_idx'), models.Index(fields=['created_at'], name='billing_inv_created_5a66c5_idx')],
            },
        ),
    ]
