# Generated by Django 6.0.7 on 2026-07-17 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_investorservicerequest'),
        ('franchises', '0006_franchiseasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_feature_in_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_feature_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_receive_priority_leads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_description_length',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_gallery_images',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FranchiseSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na aktywację'), ('active', 'Aktywna'), ('past_due', 'Płatność zaległa'), ('cancelled', 'Anulowana'), ('expired', 'Wygasła')], default='pending', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('manual_payment_status', models.CharField(choices=[('pending', 'Oczekuje'), ('paid', 'Opłacona'), ('overdue', 'Zaległa'), ('not_required', 'Nie jest wymagana')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to='franchises.franchise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franchise_subscriptions', to='billing.plan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_franchise_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ends_at', 'franchise__name'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('start', 'Zakup subskrypcji'), ('extend', 'Przedłużenie'), ('change_plan', 'Zmiana planu'), ('cancel', 'Anulowanie')], max_length=20)),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, '1 miesiąc'), (3, '3 miesiące'), (12, '12 miesięcy')], default=1)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone'), ('cancelled', 'Wycofane')], default='pending', max_length=20)),
                ('vendor_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='franchises.franchise')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_subscription_change_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='franchise_subscription_requests', to='billing.plan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_franchise_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='billing.franchisesubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='franchisesubscription',
            index=models.Index(fields=['status', 'ends_at'], name='billing_fra_status_41c897_idx'),
        ),
        migrations.AddIndex(
            model_name='franchisesubscription',
            index=models.Index(fields=['plan', 'status'], name='billing_fra_plan_id_64150f_idx'),
        ),
        migrations.AddIndex(
            model_name='franchisesubscription',
            index=models.Index(fields=['manual_payment_status'], name='billing_fra_manual__d038d4_idx'),
        ),
        migrations.AddIndex(
            model_name='franchisesubscriptionrequest',
            index=models.Index(fields=['status', 'created_at'], name='billing_fra_status_078da5_idx'),
        ),
        migrations.AddIndex(
            model_name='franchisesubscriptionrequest',
            index=models.Index(fields=['franchise', 'status'], name='billing_fra_franchi_23b45b_idx'),
        ),
        migrations.AddIndex(
            model_name='franchisesubscriptionrequest',
            index=models.Index(fields=['request_type', 'status'], name='billing_fra_request_983b4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchisesubscriptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('franchise',), name='unique_pending_subscription_request_per_franchise'),
        ),
    ]
