# Generated by Django 6.0.7 on 2026-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_franchisesubscription_billing_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsubscription',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('manual', 'Manual'), ('custom', 'Custom')], default='monthly', max_length=20),
        ),
    ]
