# Generated by Django 6.0.7 on 2026-07-14 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'franchise category',
                'verbose_name_plural': 'franchise categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=260)),
                ('description', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to='franchise_logos/')),
                ('website_url', models.URLField(blank=True)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('initial_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('royalty_fee_text', models.CharField(blank=True, max_length=160)),
                ('marketing_fee_text', models.CharField(blank=True, max_length=160)),
                ('business_type', models.CharField(choices=[('stationary', 'Stationary'), ('mobile', 'Mobile'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='stationary', max_length=20)),
                ('required_premises', models.CharField(blank=True, max_length=180)),
                ('home_based', models.BooleanField(default=False)),
                ('part_time_possible', models.BooleanField(default=False)),
                ('training_provided', models.BooleanField(default=True)),
                ('financing_available', models.BooleanField(default=False)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('franchising_since', models.PositiveIntegerField(blank=True, null=True)),
                ('total_units', models.PositiveIntegerField(blank=True, null=True)),
                ('poland_units', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('editor_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franchises', to='franchises.franchisecategory')),
            ],
            options={
                'ordering': ['-is_promoted', '-rank_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('existing_unit', 'Existing unit'), ('available_area', 'Available area'), ('headquarters', 'Headquarters')], default='existing_unit', max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='franchises.franchise')),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
    ]
