# Generated by Django 6.0.7 on 2026-07-14 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendor_organization_fields'),
        ('franchises', '0003_franchise_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('short_description', models.CharField(max_length=260)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('initial_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('royalty_fee_text', models.CharField(blank=True, max_length=160)),
                ('marketing_fee_text', models.CharField(blank=True, max_length=160)),
                ('business_type', models.CharField(choices=[('stationary', 'Stationary'), ('mobile', 'Mobile'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='stationary', max_length=20)),
                ('required_premises', models.CharField(blank=True, max_length=180)),
                ('home_based', models.BooleanField(default=False)),
                ('part_time_possible', models.BooleanField(default=False)),
                ('training_provided', models.BooleanField(default=True)),
                ('financing_available', models.BooleanField(default=False)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('franchising_since', models.PositiveIntegerField(blank=True, null=True)),
                ('total_units', models.PositiveIntegerField(blank=True, null=True)),
                ('poland_units', models.PositiveIntegerField(blank=True, null=True)),
                ('admin_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='franchises.franchise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_update_requests', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_franchise_updates', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_franchise_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['franchise', 'status'], name='franchises__franchi_f74c7f_idx'), models.Index(fields=['organization', 'status'], name='franchises__organiz_ed97d7_idx'), models.Index(fields=['submitted_by', 'status'], name='franchises__submitt_2ab791_idx'), models.Index(fields=['status', 'submitted_at'], name='franchises__status_f1dac9_idx')],
            },
        ),
    ]
