# Generated by Django 6.0.7 on 2026-07-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0004_franchiseupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='company_owned_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='data_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='data_status',
            field=models.CharField(choices=[('demo', 'Dane demonstracyjne'), ('vendor', 'Dane przekazane przez franczyzodawcę'), ('editor_verified', 'Dane zweryfikowane przez redakcję')], default='demo', max_length=20),
        ),
        migrations.AddField(
            model_name='franchise',
            name='estimated_payback_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='financial_data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='financial_performance_disclosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchise',
            name='financial_performance_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='franchise_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='franchised_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='liquid_capital_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='mature_unit_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='mature_unit_operating_profit_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='mature_unit_revenue_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='net_worth_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='renewal_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='territory_type',
            field=models.CharField(blank=True, choices=[('exclusive', 'Wyłączna'), ('protected', 'Chroniona'), ('non_exclusive', 'Niewyłączna'), ('not_disclosed', 'Do ustalenia w umowie')], max_length=20),
        ),
        migrations.AddField(
            model_name='franchise',
            name='typical_staff_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='typical_unit_size_max_sqm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='typical_unit_size_min_sqm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='unit_growth_percent_1y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='units_closed_last_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='units_opened_last_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='units_transferred_last_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='company_owned_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='data_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='data_status',
            field=models.CharField(choices=[('demo', 'Dane demonstracyjne'), ('vendor', 'Dane przekazane przez franczyzodawcę'), ('editor_verified', 'Dane zweryfikowane przez redakcję')], default='demo', max_length=20),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='estimated_payback_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='financial_data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='financial_performance_disclosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='financial_performance_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='franchise_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='franchised_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='liquid_capital_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='mature_unit_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='mature_unit_operating_profit_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='mature_unit_revenue_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='net_worth_required',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='renewal_term_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='territory_type',
            field=models.CharField(blank=True, choices=[('exclusive', 'Wyłączna'), ('protected', 'Chroniona'), ('non_exclusive', 'Niewyłączna'), ('not_disclosed', 'Do ustalenia w umowie')], max_length=20),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='typical_staff_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='typical_unit_size_max_sqm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='typical_unit_size_min_sqm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='unit_growth_percent_1y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='units_closed_last_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='units_opened_last_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseupdaterequest',
            name='units_transferred_last_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
