# Generated by Django 6.0.7 on 2026-07-17 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0005_franchise_company_owned_units_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('image', 'Zdjęcie'), ('document', 'Dokument')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=260)),
                ('file', models.FileField(upload_to='franchise_assets/%Y/%m/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje na moderację'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='franchises.franchise')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_franchise_assets', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_franchise_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['franchise', 'asset_type', 'status'], name='franchises__franchi_e92492_idx'), models.Index(fields=['status', 'created_at'], name='franchises__status_562cbb_idx')],
            },
        ),
    ]
