# Generated by Django 6.0.7 on 2026-07-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0006_franchiseasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseResearchField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field', models.CharField(max_length=500)),
                ('requirement', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=40)),
                ('checker_status', models.CharField(max_length=40)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('normalized_field_id', models.CharField(blank=True, max_length=100)),
                ('accepted_claim_ids', models.JSONField(default=list)),
                ('needs_review_claim_ids', models.JSONField(default=list)),
                ('rejected_claim_ids', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['task__sort_order', 'target_field'],
            },
        ),
        migrations.AlterField(
            model_name='franchise',
            name='data_status',
            field=models.CharField(choices=[('demo', 'Dane demonstracyjne'), ('vendor', 'Dane przekazane przez franczyzodawcę'), ('editor_verified', 'Dane zweryfikowane przez redakcję'), ('research_reviewed', 'Research zatwierdzony przez redakcję'), ('research_with_gaps', 'Research zatwierdzony z brakami')], default='demo', max_length=20),
        ),
        migrations.AlterField(
            model_name='franchiseupdaterequest',
            name='data_status',
            field=models.CharField(choices=[('demo', 'Dane demonstracyjne'), ('vendor', 'Dane przekazane przez franczyzodawcę'), ('editor_verified', 'Dane zweryfikowane przez redakcję'), ('research_reviewed', 'Research zatwierdzony przez redakcję'), ('research_with_gaps', 'Research zatwierdzony z brakami')], default='demo', max_length=20),
        ),
        migrations.CreateModel(
            name='FranchiseResearchImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(unique=True)),
                ('normalization_id', models.UUIDField(unique=True)),
                ('plan_run_id', models.UUIDField()),
                ('search_id', models.UUIDField()),
                ('extraction_id', models.UUIDField()),
                ('check_id', models.UUIDField()),
                ('target_country', models.CharField(max_length=2)),
                ('depth', models.CharField(max_length=30)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('approved_with_gaps', 'Approved with gaps')], max_length=30)),
                ('reviewer', models.CharField(max_length=300)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('incomplete_input_acknowledged', models.BooleanField(default=False)),
                ('checker_passed', models.BooleanField()),
                ('scope_complete', models.BooleanField()),
                ('quality_score', models.PositiveSmallIntegerField()),
                ('quality_threshold', models.PositiveSmallIntegerField()),
                ('planned_tasks', models.PositiveIntegerField()),
                ('evaluated_tasks', models.PositiveIntegerField()),
                ('planned_fields', models.PositiveIntegerField()),
                ('evaluated_fields', models.PositiveIntegerField()),
                ('normalized_values_count', models.PositiveIntegerField()),
                ('source_count', models.PositiveIntegerField()),
                ('claim_count', models.PositiveIntegerField()),
                ('citation_count', models.PositiveIntegerField()),
                ('review_reference', models.TextField()),
                ('review_sha256', models.CharField(max_length=64)),
                ('normalized_reference', models.TextField()),
                ('normalized_sha256', models.CharField(max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_imports', to='franchises.franchise')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=200)),
                ('target_field', models.CharField(max_length=500)),
                ('value_text', models.TextField()),
                ('asserted_by_text', models.TextField(blank=True)),
                ('as_of_text', models.CharField(blank=True, max_length=300)),
                ('unit_text', models.CharField(blank=True, max_length=300)),
                ('currency_text', models.CharField(blank=True, max_length=100)),
                ('publication_date_text', models.CharField(blank=True, max_length=300)),
                ('effective_date_text', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('checker_verdict', models.CharField(blank=True, max_length=40)),
                ('semantic_fit', models.CharField(blank=True, max_length=40)),
                ('source_support', models.CharField(blank=True, max_length=40)),
                ('issue_codes', models.JSONField(default=list)),
                ('is_eligible', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField()),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='franchises.franchiseresearchfield')),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='franchises.franchiseresearchimport')),
            ],
            options={
                'ordering': ['task_id', 'target_field', 'claim_id'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('plan', 'Plan'), ('search', 'Search'), ('extraction', 'Extraction'), ('check', 'Check'), ('normalization', 'Normalization'), ('review', 'Review')], max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('schema_version', models.CharField(blank=True, max_length=30)),
                ('prompt_version', models.CharField(blank=True, max_length=60)),
                ('reference', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='franchises.franchiseresearchimport')),
            ],
            options={
                'ordering': ['artifact_type'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('canonical_url', models.URLField(max_length=4000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_type', models.CharField(max_length=60)),
                ('origin', models.CharField(max_length=60)),
                ('provider_observed', models.BooleanField(default=False)),
                ('retrieval_status', models.CharField(blank=True, max_length=60)),
                ('task_ids', models.JSONField(default=list)),
                ('raw_payload', models.JSONField()),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='franchises.franchiseresearchimport')),
            ],
            options={
                'ordering': ['source_type', 'title', 'source_id'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_id', models.CharField(max_length=100)),
                ('passage_id', models.CharField(max_length=100)),
                ('document_id', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('locator', models.CharField(blank=True, max_length=500)),
                ('text_sha256', models.CharField(max_length=64)),
                ('start_char', models.PositiveIntegerField(blank=True, null=True)),
                ('end_char', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='franchises.franchiseresearchimport')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='franchises.franchiseresearchsource')),
            ],
            options={
                'ordering': ['source_id', 'citation_id'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('catalog_question_id', models.CharField(max_length=200)),
                ('section_id', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=500)),
                ('question', models.TextField()),
                ('requirement', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=40)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('raw_payload', models.JSONField()),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='franchises.franchiseresearchimport')),
            ],
            options={
                'ordering': ['sort_order', 'task_id'],
            },
        ),
        migrations.AddField(
            model_name='franchiseresearchfield',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='franchises.franchiseresearchtask'),
        ),
        migrations.CreateModel(
            name='FranchiseResearchValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_value_id', models.CharField(max_length=100)),
                ('value_type', models.CharField(max_length=30)),
                ('canonical_text', models.TextField()),
                ('number_min_text', models.CharField(blank=True, max_length=200)),
                ('number_max_text', models.CharField(blank=True, max_length=200)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('precision', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('raw_value_texts', models.JSONField(default=list)),
                ('citation_ids', models.JSONField(default=list)),
                ('source_ids', models.JSONField(default=list)),
                ('needs_corroboration', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='franchises.franchiseresearchfield')),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='franchises.franchiseresearchimport')),
            ],
            options={
                'ordering': ['field__task__sort_order', 'field__target_field', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchValueClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_values', to='franchises.franchiseresearchclaim')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_claims', to='franchises.franchiseresearchvalue')),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseResearchClaimCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_claims', to='franchises.franchiseresearchcitation')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_citations', to='franchises.franchiseresearchclaim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'citation'), name='unique_research_claim_citation')],
            },
        ),
        migrations.AddIndex(
            model_name='franchiseresearchimport',
            index=models.Index(fields=['franchise', 'is_current'], name='franchises__franchi_00d556_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchimport',
            index=models.Index(fields=['plan_run_id'], name='franchises__plan_ru_f23b35_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchimport',
            index=models.Index(fields=['decision', 'imported_at'], name='franchises__decisio_69e66e_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchclaim',
            index=models.Index(fields=['target_field', 'checker_verdict'], name='franchises__target__56c230_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchclaim',
            constraint=models.UniqueConstraint(fields=('research_import', 'claim_id'), name='unique_research_claim_per_import'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchartifact',
            constraint=models.UniqueConstraint(fields=('research_import', 'artifact_type'), name='unique_research_artifact_type_per_import'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchsource',
            constraint=models.UniqueConstraint(fields=('research_import', 'source_id'), name='unique_research_source_per_import'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchcitation',
            constraint=models.UniqueConstraint(fields=('research_import', 'citation_id'), name='unique_research_citation_per_import'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchtask',
            constraint=models.UniqueConstraint(fields=('research_import', 'task_id'), name='unique_research_task_per_import'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchfield',
            index=models.Index(fields=['target_field', 'status'], name='franchises__target__65f0bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchfield',
            constraint=models.UniqueConstraint(fields=('task', 'target_field'), name='unique_research_field_per_task'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchvalue',
            constraint=models.UniqueConstraint(fields=('research_import', 'normalized_value_id'), name='unique_research_value_per_import'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchvalueclaim',
            constraint=models.UniqueConstraint(fields=('value', 'claim'), name='unique_research_value_claim'),
        ),
    ]
