# Generated by Django 6.0.7 on 2026-07-20 19:28

import django.db.models.deletion
import franchises.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0007_franchiseresearchfield_alter_franchise_data_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseResearchWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('normalization_id', models.UUIDField(unique=True)),
                ('plan_run_id', models.UUIDField()),
                ('target_country', models.CharField(max_length=2)),
                ('depth', models.CharField(max_length=30)),
                ('profile_id', models.CharField(blank=True, max_length=80)),
                ('iteration', models.PositiveIntegerField()),
                ('normalized_reference', models.TextField()),
                ('normalized_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('review', 'W trakcie weryfikacji'), ('ready', 'Gotowe do zatwierdzenia'), ('approved_with_gaps', 'Zatwierdzone z udokumentowanymi brakami'), ('rejected', 'Odrzucone')], default='review', max_length=30)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('quality_threshold', models.PositiveSmallIntegerField(default=80)),
                ('checker_passed', models.BooleanField(default=False)),
                ('scope_complete', models.BooleanField(default=False)),
                ('planned_tasks', models.PositiveIntegerField(default=0)),
                ('evaluated_tasks', models.PositiveIntegerField(default=0)),
                ('planned_fields', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('normalized_values_count', models.PositiveIntegerField(default=0)),
                ('stage_summary', models.JSONField(default=list)),
                ('cost_summary', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_research_workspaces', to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_workspaces', to='franchises.franchise')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_research_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchReviewField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_field_id', models.CharField(blank=True, max_length=100)),
                ('task_id', models.CharField(max_length=200)),
                ('task_title', models.CharField(max_length=500)),
                ('target_field', models.CharField(max_length=500)),
                ('requirement', models.CharField(blank=True, max_length=30)),
                ('priority', models.CharField(blank=True, max_length=30)),
                ('pipeline_status', models.CharField(max_length=40)),
                ('checker_status', models.CharField(blank=True, max_length=40)),
                ('proposed_values', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('source_ids', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('pending', 'Do sprawdzenia'), ('accepted', 'Zaakceptowane'), ('accepted_edited', 'Poprawione i zaakceptowane'), ('rejected', 'Odrzucone'), ('documented_gap', 'Sprawdzono — brak danych')], default='pending', max_length=30)),
                ('reviewer_value', models.TextField(blank=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_field_decisions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_fields', to='franchises.franchiseresearchworkspace')),
            ],
            options={
                'ordering': ['sort_order', 'target_field'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='franchises.franchiseresearchworkspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, storage=franchises.models.PrivateResearchStorage(), upload_to=franchises.models.research_document_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Umowa / wzór umowy'), ('disclosure', 'Pakiet informacyjny / oferta'), ('financial', 'Dane finansowe'), ('legal', 'Dokument prawny / rejestrowy'), ('presentation', 'Prezentacja / materiały sieci'), ('other', 'Inny dokument')], max_length=30)),
                ('access_level', models.CharField(choices=[('internal', 'Wewnętrzny'), ('restricted', 'Poufny — ograniczony dostęp'), ('public_source', 'Materiał z publicznego źródła')], default='internal', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Czeka na analizę'), ('ready', 'Uwzględniony ręcznie')], default='pending', max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='franchises.franchiseresearchworkspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='franchiseresearchworkspace',
            index=models.Index(fields=['franchise', 'status'], name='franchises__franchi_461053_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchworkspace',
            index=models.Index(fields=['status', 'updated_at'], name='franchises__status_83feed_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchreviewfield',
            index=models.Index(fields=['workspace', 'decision'], name='franchises__workspa_88249e_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchreviewfield',
            index=models.Index(fields=['workspace', 'pipeline_status'], name='franchises__workspa_ceac76_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchreviewfield',
            constraint=models.UniqueConstraint(fields=('workspace', 'task_id', 'target_field'), name='unique_workbench_field_per_task'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchevent',
            index=models.Index(fields=['workspace', 'created_at'], name='franchises__workspa_f17b8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearchdocument',
            constraint=models.UniqueConstraint(fields=('workspace', 'sha256'), name='unique_workbench_document_content'),
        ),
    ]
