# Generated by Django 6.0.7 on 2026-07-20 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0008_franchiseresearchworkspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseresearchreviewfield',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='supported_review_fields', to='franchises.franchiseresearchdocument'),
        ),
        migrations.CreateModel(
            name='FranchiseResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('loop', 'Kontynuuj research'), ('check', 'Ponów kontrolę jakości'), ('normalize', 'Utwórz nowy draft danych')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'W trakcie'), ('succeeded', 'Zakończone'), ('failed', 'Błąd'), ('cancelled', 'Anulowane')], default='queued', max_length=20)),
                ('input_reference', models.TextField()),
                ('input_sha256', models.CharField(max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('current_stage', models.CharField(default='Oczekiwanie na worker', max_length=120)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('result_summary', models.JSONField(default=dict)),
                ('cost_summary', models.JSONField(default=dict)),
                ('result_loop_reference', models.TextField(blank=True)),
                ('result_loop_sha256', models.CharField(blank=True, max_length=64)),
                ('result_check_reference', models.TextField(blank=True)),
                ('result_check_sha256', models.CharField(blank=True, max_length=64)),
                ('result_normalized_reference', models.TextField(blank=True)),
                ('result_normalized_sha256', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_research_jobs', to=settings.AUTH_USER_MODEL)),
                ('result_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_jobs', to='franchises.franchiseresearchworkspace')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='franchises.franchiseresearchworkspace')),
            ],
            options={
                'ordering': ['-queued_at', '-id'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='franchises__status_42943b_idx'), models.Index(fields=['workspace', 'queued_at'], name='franchises__workspa_847cb9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('workspace',), name='unique_active_research_job_per_workspace')],
            },
        ),
    ]
