# Generated by Django 6.0.7 on 2026-07-20 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0009_franchiseresearchreviewfield_supporting_documents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseresearchartifact',
            name='artifact_type',
            field=models.CharField(choices=[('plan', 'Plan'), ('search', 'Search'), ('extraction', 'Extraction'), ('check', 'Check'), ('normalization', 'Normalization'), ('review', 'Review'), ('finalization', 'Workbench finalization')], max_length=20),
        ),
        migrations.AlterField(
            model_name='franchiseresearchworkspace',
            name='status',
            field=models.CharField(choices=[('review', 'W trakcie weryfikacji'), ('ready', 'Gotowe do zatwierdzenia'), ('approved', 'Zatwierdzone'), ('approved_with_gaps', 'Zatwierdzone z udokumentowanymi brakami'), ('rejected', 'Odrzucone')], default='review', max_length=30),
        ),
        migrations.CreateModel(
            name='FranchiseResearchFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalization_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('approved_with_gaps', 'Approved with gaps')], max_length=30)),
                ('reviewer_name', models.CharField(max_length=300)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('normalized_sha256', models.CharField(max_length=64)),
                ('workspace_state_sha256', models.CharField(max_length=64)),
                ('artifact_reference', models.TextField()),
                ('artifact_sha256', models.CharField(max_length=64)),
                ('field_count', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('edited_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('gap_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('finalized_at', models.DateTimeField()),
                ('research_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workbench_finalizations', to='franchises.franchiseresearchimport')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_finalizations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finalization', to='franchises.franchiseresearchworkspace')),
            ],
            options={
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchEditorialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=30)),
                ('access_level', models.CharField(max_length=30)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('workbench_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finalized_snapshots', to='franchises.franchiseresearchdocument')),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='franchises.franchiseresearchfinalization')),
            ],
            options={
                'ordering': ['original_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseResearchEditorialDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('task_title', models.CharField(max_length=500)),
                ('target_field', models.CharField(max_length=500)),
                ('requirement', models.CharField(blank=True, max_length=30)),
                ('priority', models.CharField(blank=True, max_length=30)),
                ('pipeline_status', models.CharField(max_length=40)),
                ('checker_status', models.CharField(blank=True, max_length=40)),
                ('decision', models.CharField(choices=[('pending', 'Do sprawdzenia'), ('accepted', 'Zaakceptowane'), ('accepted_edited', 'Poprawione i zaakceptowane'), ('rejected', 'Odrzucone'), ('documented_gap', 'Sprawdzono — brak danych')], max_length=30)),
                ('value_origin', models.CharField(choices=[('ai', 'AI proposal approved by a human'), ('human', 'Human supplied or corrected'), ('none', 'No publishable value')], max_length=10)),
                ('effective_value', models.TextField(blank=True)),
                ('proposed_values', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('source_ids', models.JSONField(default=list)),
                ('reviewer_note', models.TextField(blank=True)),
                ('decided_by_name', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('research_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_decisions', to='franchises.franchiseresearchfield')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='field_decisions', to='franchises.franchiseresearcheditorialdocument')),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_decisions', to='franchises.franchiseresearchfinalization')),
            ],
            options={
                'ordering': ['research_field__task__sort_order', 'target_field', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='franchiseresearchfinalization',
            index=models.Index(fields=['research_import', 'finalized_at'], name='franchises__researc_4db06b_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearchfinalization',
            index=models.Index(fields=['decision', 'finalized_at'], name='franchises__decisio_eb70c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearcheditorialdocument',
            constraint=models.UniqueConstraint(fields=('finalization', 'workbench_document'), name='unique_finalized_workbench_document'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearcheditorialdecision',
            index=models.Index(fields=['finalization', 'decision'], name='franchises__finaliz_234861_idx'),
        ),
        migrations.AddIndex(
            model_name='franchiseresearcheditorialdecision',
            index=models.Index(fields=['target_field', 'decision'], name='franchises__target__6c46fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='franchiseresearcheditorialdecision',
            constraint=models.UniqueConstraint(fields=('finalization', 'task_id', 'target_field'), name='unique_editorial_field_per_finalization'),
        ),
    ]
