# Generated by Django 6.0.7 on 2026-07-21 14:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_release_and_profile(apps, schema_editor):
    Finalization = apps.get_model("franchises", "FranchiseResearchFinalization")
    Import = apps.get_model("franchises", "FranchiseResearchImport")
    franchise_ids = (
        Finalization.objects.values_list("research_import__franchise_id", flat=True)
        .distinct()
    )
    for franchise_id in franchise_ids:
        releases = Finalization.objects.filter(
            research_import__franchise_id=franchise_id
        ).order_by("finalized_at", "id")
        previous = None
        for number, finalization in enumerate(releases, start=1):
            Finalization.objects.filter(pk=finalization.pk).update(
                release_number=number,
                supersedes_id=previous,
            )
            previous = finalization.pk
    for finalization in Finalization.objects.select_related(
        "workspace", "research_import"
    ):
        if finalization.workspace.profile_id and not finalization.research_import.profile_id:
            Import.objects.filter(pk=finalization.research_import_id).update(
                profile_id=finalization.workspace.profile_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0010_alter_franchiseresearchartifact_artifact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseresearchfinalization',
            name='release_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='franchiseresearchfinalization',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='franchises.franchiseresearchfinalization'),
        ),
        migrations.AddField(
            model_name='franchiseresearchimport',
            name='profile_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='franchiseresearchreviewfield',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_forward_to', to='franchises.franchiseresearchreviewfield'),
        ),
        migrations.AlterField(
            model_name='franchiseresearchjob',
            name='kind',
            field=models.CharField(choices=[('loop', 'Kontynuuj research'), ('check', 'Ponów kontrolę jakości'), ('normalize', 'Utwórz nowy draft danych'), ('finalize', 'Zamroź i opublikuj wersję')], max_length=20),
        ),
        migrations.RunPython(backfill_release_and_profile, migrations.RunPython.noop),
    ]
