# Generated by Django 6.0.7 on 2026-07-21 16:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0011_franchiseresearchfinalization_release_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseResearchLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_country', models.CharField(default='PL', max_length=2)),
                ('profile_id', models.CharField(max_length=80)),
                ('known_legal_name', models.CharField(blank=True, max_length=300)),
                ('known_official_website', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'W trakcie'), ('succeeded', 'Zakończone'), ('failed', 'Błąd'), ('cancelled', 'Anulowane')], default='queued', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('current_stage', models.CharField(default='Oczekiwanie na worker', max_length=120)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('result_summary', models.JSONField(default=dict)),
                ('cost_summary', models.JSONField(default=dict)),
                ('plan_reference', models.TextField(blank=True)),
                ('plan_sha256', models.CharField(blank=True, max_length=64)),
                ('sources_reference', models.TextField(blank=True)),
                ('sources_sha256', models.CharField(blank=True, max_length=64)),
                ('extractions_reference', models.TextField(blank=True)),
                ('extractions_sha256', models.CharField(blank=True, max_length=64)),
                ('check_reference', models.TextField(blank=True)),
                ('check_sha256', models.CharField(blank=True, max_length=64)),
                ('normalized_reference', models.TextField(blank=True)),
                ('normalized_sha256', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_launches', to='franchises.franchise')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_research_launches', to=settings.AUTH_USER_MODEL)),
                ('result_workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_launches', to='franchises.franchiseresearchworkspace')),
            ],
            options={
                'ordering': ['-queued_at', '-id'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='franchises__status_63aa27_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('franchise',), name='unique_active_research_launch_per_franchise')],
            },
        ),
    ]
