# Generated by Django 6.0.7 on 2026-07-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0012_franchiseresearchlaunch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseResearchPublishedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_field', models.CharField(max_length=500)),
                ('franchise_attribute', models.CharField(max_length=80)),
                ('value_origin', models.CharField(choices=[('ai', 'AI proposal approved by a human'), ('human', 'Human supplied or corrected'), ('none', 'No publishable value')], max_length=10)),
                ('effective_value', models.TextField()),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('projected_value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('projected', 'Opublikowano na profilu'), ('skipped', 'Pozostawiono tylko w raporcie')], max_length=20)),
                ('issue_code', models.CharField(blank=True, max_length=80)),
                ('is_current', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('editorial_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_projection', to='franchises.franchiseresearcheditorialdecision')),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_fields', to='franchises.franchiseresearchfinalization')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_published_fields', to='franchises.franchise')),
            ],
            options={
                'ordering': ['franchise_attribute', 'target_field', 'id'],
                'indexes': [models.Index(fields=['franchise', 'is_current'], name='franchises__franchi_0307c2_idx'), models.Index(fields=['finalization', 'status'], name='franchises__finaliz_579ffd_idx')],
                'constraints': [models.UniqueConstraint(fields=('finalization', 'franchise_attribute'), name='unique_publication_attribute_per_finalization'), models.UniqueConstraint(condition=models.Q(('is_current', True), ('status', 'projected')), fields=('franchise', 'franchise_attribute'), name='unique_current_research_publication_attribute')],
            },
        ),
    ]
