# Generated by Django 6.0.7 on 2026-07-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_backfill_allauth_email_addresses'),
        ('billing', '0007_organizationsubscription_billing_interval'),
        ('franchises', '0006_franchiseasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('active_customer', 'Active customer'), ('churned', 'Churned'), ('not_fit', 'Not a fit')], default='prospect', max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_accounts', to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_accounts', to='franchises.franchise')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_accounts', to='accounts.organization')),
            ],
            options={
                'ordering': ['next_follow_up_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='backoffice.salesaccount')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('contacted', 'Contacted'), ('discovery', 'Discovery'), ('demo', 'Demo'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('churn_risk', 'Churn risk'), ('churned', 'Churned')], default='prospecting', max_length=20)),
                ('expected_monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_annual_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probability', models.PositiveIntegerField(default=10)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('churn_reason', models.CharField(blank=True, max_length=255)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('churned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='backoffice.salesaccount')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_opportunities', to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunities', to='franchises.franchise')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_opportunities', to='accounts.organization')),
            ],
            options={
                'ordering': ['next_follow_up_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note'), ('task', 'Task'), ('demo', 'Demo'), ('proposal_sent', 'Proposal sent'), ('contract_sent', 'Contract sent'), ('negotiation', 'Negotiation'), ('status_change', 'Status change')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('old_stage', models.CharField(blank=True, max_length=50)),
                ('new_stage', models.CharField(blank=True, max_length=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='backoffice.salesaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_activities', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='backoffice.salescontact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='backoffice.salesopportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('new_subscription', 'New subscription'), ('renewal', 'Renewal'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('cancellation', 'Cancellation'), ('churn', 'Churn'), ('reactivation', 'Reactivation'), ('manual_adjustment', 'Manual adjustment')], max_length=24)),
                ('billing_interval', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='PLN', max_length=10)),
                ('mrr_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arr_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('effective_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revenue_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_events', to='accounts.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events', to='billing.plan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_events', to='billing.organizationsubscription')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'effective_at'], name='backoffice__organiz_a8a69d_idx'), models.Index(fields=['event_type', 'effective_at'], name='backoffice__event_t_8c9bd3_idx'), models.Index(fields=['effective_at'], name='backoffice__effecti_e73823_idx'), models.Index(fields=['billing_interval'], name='backoffice__billing_894939_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='salesaccount',
            index=models.Index(fields=['status'], name='backoffice__status_2bd61c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesaccount',
            index=models.Index(fields=['assigned_to', 'status'], name='backoffice__assigne_7c1694_idx'),
        ),
        migrations.AddIndex(
            model_name='salesaccount',
            index=models.Index(fields=['next_follow_up_at'], name='backoffice__next_fo_e0a569_idx'),
        ),
        migrations.AddIndex(
            model_name='salesaccount',
            index=models.Index(fields=['last_activity_at'], name='backoffice__last_ac_eb7b75_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontact',
            index=models.Index(fields=['account', 'is_primary'], name='backoffice__account_b113d4_idx'),
        ),
        migrations.AddIndex(
            model_name='salescontact',
            index=models.Index(fields=['email'], name='backoffice__email_571771_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['stage'], name='backoffice__stage_28c09f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['assigned_to', 'stage'], name='backoffice__assigne_244f38_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['next_follow_up_at'], name='backoffice__next_fo_6991db_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['expected_close_date'], name='backoffice__expecte_cf168a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesopportunity',
            index=models.Index(fields=['last_activity_at'], name='backoffice__last_ac_d3cd60_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['account', 'created_at'], name='backoffice__account_9a1364_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['opportunity', 'created_at'], name='backoffice__opportu_d86b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['activity_type', 'created_at'], name='backoffice__activit_03efe6_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['due_at'], name='backoffice__due_at_9d9f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['completed_at'], name='backoffice__complet_181817_idx'),
        ),
        migrations.AddIndex(
            model_name='salesactivity',
            index=models.Index(fields=['created_by', 'created_at'], name='backoffice__created_7c45e6_idx'),
        ),
    ]
