# Generated by Django 6.0.7 on 2026-07-14 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0003_franchise_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('featured_image', models.FileField(blank=True, upload_to='content/articles/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.articlecategory')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='content_art_status_4645e7_idx'), models.Index(fields=['slug'], name='content_art_slug_d82f31_idx'), models.Index(fields=['is_featured'], name='content_art_is_feat_f4f830_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=260)),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=220)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('canonical_url', models.URLField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('', 'Any'), ('stationary', 'Stationary'), ('mobile', 'Mobile'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=20)),
                ('home_based', models.BooleanField(blank=True, null=True)),
                ('part_time_possible', models.BooleanField(blank=True, null=True)),
                ('training_provided', models.BooleanField(blank=True, null=True)),
                ('financing_available', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='franchises.franchisecategory')),
                ('selected_franchises', models.ManyToManyField(blank=True, related_name='landing_pages', to='franchises.franchise')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='content_lan_status_095035_idx'), models.Index(fields=['slug'], name='content_lan_slug_846222_idx'), models.Index(fields=['is_featured'], name='content_lan_is_feat_36052f_idx'), models.Index(fields=['max_investment'], name='content_lan_max_inv_179ec7_idx')],
            },
        ),
    ]
