from django.urls import path

from .views import (
    internal_home_view,
    internal_revenue_dashboard_view,
    internal_sales_dashboard_view,
    internal_sales_opportunity_detail_view,
    internal_subscriptions_view,
    research_campaign_cancel_view,
    research_campaign_create_view,
    research_campaign_detail_view,
    research_campaign_list_view,
    research_campaign_retry_view,
    research_campaign_status_view,
    research_benchmark_brand_view,
    research_benchmark_campaign_create_view,
    research_benchmark_download_view,
    research_benchmark_export_view,
    research_benchmark_field_update_view,
    research_benchmark_gold_brand_view,
    research_benchmark_gold_promote_view,
    research_benchmark_gold_view,
    research_benchmark_metrics_update_view,
    research_benchmark_view,
    research_workbench_decision_view,
    research_workbench_detail_view,
    research_workbench_document_download_view,
    research_workbench_document_upload_view,
    research_workbench_field_action_view,
    research_workbench_field_edit_view,
    research_workbench_finalize_view,
    research_workbench_job_cancel_view,
    research_workbench_job_queue_view,
    research_workbench_job_status_view,
    research_workbench_list_view,
    research_launch_cancel_view,
    research_launch_create_view,
    research_launch_detail_view,
    research_launch_retry_view,
    research_launch_status_view,
)


app_name = "backoffice"

urlpatterns = [
    path("internal/", internal_home_view, name="internal_home"),
    path("internal/revenue/", internal_revenue_dashboard_view, name="revenue_dashboard"),
    path("internal/revenue/subscriptions/", internal_subscriptions_view, name="subscriptions"),
    path("internal/sales/", internal_sales_dashboard_view, name="sales_dashboard"),
    path("internal/sales/opportunities/<int:pk>/", internal_sales_opportunity_detail_view, name="sales_opportunity_detail"),
    path("internal/research/", research_workbench_list_view, name="research_workbench_list"),
    path("internal/research/benchmark/", research_benchmark_view, name="research_benchmark"),
    path("internal/research/benchmark/campaign/create/", research_benchmark_campaign_create_view, name="research_benchmark_campaign_create"),
    path("internal/research/benchmark/export/", research_benchmark_export_view, name="research_benchmark_export"),
    path("internal/research/benchmark/download/<slug:artifact>/", research_benchmark_download_view, name="research_benchmark_download"),
    path("internal/research/benchmark/gold/", research_benchmark_gold_view, name="research_benchmark_gold"),
    path("internal/research/benchmark/gold/<slug:brand_slug>/promote/", research_benchmark_gold_promote_view, name="research_benchmark_gold_promote"),
    path("internal/research/benchmark/gold/<slug:brand_slug>/", research_benchmark_gold_brand_view, name="research_benchmark_gold_brand"),
    path("internal/research/benchmark/<slug:brand_slug>/", research_benchmark_brand_view, name="research_benchmark_brand"),
    path("internal/research/benchmark/<slug:brand_slug>/<slug:kind>/field/", research_benchmark_field_update_view, name="research_benchmark_field_update"),
    path("internal/research/benchmark/<slug:brand_slug>/<slug:kind>/metrics/", research_benchmark_metrics_update_view, name="research_benchmark_metrics_update"),
    path("internal/research/campaigns/", research_campaign_list_view, name="research_campaign_list"),
    path("internal/research/campaigns/new/", research_campaign_create_view, name="research_campaign_create"),
    path("internal/research/campaigns/<uuid:campaign_id>/", research_campaign_detail_view, name="research_campaign_detail"),
    path("internal/research/campaigns/<uuid:campaign_id>/status/", research_campaign_status_view, name="research_campaign_status"),
    path("internal/research/campaigns/<uuid:campaign_id>/cancel/", research_campaign_cancel_view, name="research_campaign_cancel"),
    path("internal/research/campaigns/<uuid:campaign_id>/retry/", research_campaign_retry_view, name="research_campaign_retry"),
    path("internal/research/new/", research_launch_create_view, name="research_launch_create"),
    path("internal/research/runs/<uuid:launch_id>/", research_launch_detail_view, name="research_launch_detail"),
    path("internal/research/runs/<uuid:launch_id>/status/", research_launch_status_view, name="research_launch_status"),
    path("internal/research/runs/<uuid:launch_id>/cancel/", research_launch_cancel_view, name="research_launch_cancel"),
    path("internal/research/runs/<uuid:launch_id>/retry/", research_launch_retry_view, name="research_launch_retry"),
    path("internal/research/<uuid:workspace_id>/", research_workbench_detail_view, name="research_workbench_detail"),
    path("internal/research/<uuid:workspace_id>/fields/<int:pk>/edit/", research_workbench_field_edit_view, name="research_workbench_field_edit"),
    path("internal/research/<uuid:workspace_id>/fields/<int:pk>/<str:action>/", research_workbench_field_action_view, name="research_workbench_field_action"),
    path("internal/research/<uuid:workspace_id>/documents/upload/", research_workbench_document_upload_view, name="research_workbench_document_upload"),
    path("internal/research/<uuid:workspace_id>/documents/<int:pk>/download/", research_workbench_document_download_view, name="research_workbench_document_download"),
    path("internal/research/<uuid:workspace_id>/jobs/queue/", research_workbench_job_queue_view, name="research_workbench_job_queue"),
    path("internal/research/<uuid:workspace_id>/jobs/<uuid:job_id>/cancel/", research_workbench_job_cancel_view, name="research_workbench_job_cancel"),
    path("internal/research/<uuid:workspace_id>/jobs/<uuid:job_id>/status/", research_workbench_job_status_view, name="research_workbench_job_status"),
    path("internal/research/<uuid:workspace_id>/decision/<str:action>/", research_workbench_decision_view, name="research_workbench_decision"),
    path("internal/research/<uuid:workspace_id>/finalize/", research_workbench_finalize_view, name="research_workbench_finalize"),
]
