# Generated by Django 5.0.14 on 2026-07-13 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=2048)),
                ('full_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_type', models.CharField(blank=True, max_length=120)),
                ('franchise_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('referrer', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
