# Generated by Django 6.0.7 on 2026-07-15 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_backfill_allauth_email_addresses'),
        ('franchises', '0004_franchiseupdaterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimProfileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('claimant_name', models.CharField(max_length=160)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('claimant_phone', models.CharField(blank=True, max_length=40)),
                ('claimant_role', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(max_length=160)),
                ('company_website', models.URLField(blank=True)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('proof_url', models.URLField(blank=True)),
                ('proof_file', models.FileField(blank=True, upload_to='onboarding/claim_proofs/')),
                ('privacy_consent', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='franchises.franchise')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_franchise_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_claim_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['franchise', 'status'], name='onboarding__franchi_6b50ff_idx'), models.Index(fields=['user', 'status'], name='onboarding__user_id_c41d2f_idx'), models.Index(fields=['status', 'created_at'], name='onboarding__status_174efb_idx'), models.Index(fields=['claimant_email'], name='onboarding__claiman_be7b67_idx'), models.Index(fields=['company_email'], name='onboarding__company_6e81c3_idx')],
            },
        ),
    ]
